goldenfish_homepage:
    path:     /index
    defaults: { _controller: GoldenfishBundle:Default:index }

application_interface:
    path:    /app
    defaults: { _controller: GoldenfishBundle:App:indexApp}

add_note:
    path:    /app/add
    defaults: { _controller: GoldenfishBundle:App:addNote}

save_note:
    path:    /app/save
    defaults: { _controller: GoldenfishBundle:App:saveNote}

remove_trailing_slash:
    path: /{url}
    defaults: { _controller: GoldenfishBundle:Default:removeTrailingSlash }
    requirements:
        url: .*/$
    methods: [GET]

list_note:
    path:    /app/list
    defaults: { _controller: GoldenfishBundle:App:viewListNote }

partage_note:
    path: /partage/{id}
    defaults: { _controller: GoldenfishBundle:App:partageNote }
    requirements:
        id: \d+
