goldenfish_homepage:
    path:     /index
    defaults: { _controller: GoldenfishBundle:Default:index }

application_interface:
    path:    /app
    defaults: { _controller: GoldenfishBundle:App:indexApp}

add_note:
    path:    /app/add
    defaults: { _controller: GoldenfishBundle:App:addNote}

save_note:
    path:    /app/save
    defaults: { _controller: GoldenfishBundle:App:saveNote}