<?php

namespace Goldenfish\GoldenfishBundle\Entity;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNoteWithUser($id)
	{
		$qb = $this->_em->createQuery(
			'SELECT n
			FROM GoldenfishBundle:Note n
			JOIN n.usernote u, GoldenfishBundle:UserNote un
			WHERE un.user = :id AND un.droit = :droit')->setParameter('id', $id)->setParameter('droit', 'Propriétaire');
		$results = $qb->getResult();

		return $results;
	}

	public function getNotePartageWithUser($id)
	{
		$qb = $this->_em->createQuery(
			'SELECT n
			FROM GoldenfishBundle:Note n
			JOIN n.usernote u, GoldenfishBundle:UserNote un
			WHERE un.user = :id AND un.droit = :droit')->setParameter('id', $id)->setParameter('droit', 'Modification');
		$results = $qb->getResult();

		return $results;
	}
}
