<?php

namespace Goldenfish\GoldenfishBundle\Entity;

/**
 * NoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class NoteRepository extends \Doctrine\ORM\EntityRepository
{
	public function getNoteWithUser($id)
	{
		$qb = $this->_em->createQuery(
			'SELECT n
			FROM GoldenfishBundle:Note n
			WHERE n.user = :id')->setParameter('id', $id);
		$results = $qb->getResult();

		return $results;
	}
}
