<?php

namespace Goldenfish\GoldenfishBundle\Entity;

/**
 * UserNoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserNoteRepository extends \Doctrine\ORM\EntityRepository
{
}
